{% set name = "dagster_pagerduty" %}
{% set version = "0.28.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2a53cc3c3f516db33165df88fb5cbeac027a3e4e12193f2fb56d995bcddcdb1e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - pypd 1.1.*

test:
  imports:
    - dagster_pagerduty

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-pagerduty"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for pagerduty Dagster framework components."

extra:
  recipe-maintainers:
    - xhochy
